-- V1: Tax rule engine schema (PLAN.md §6 / §10). No seed data here — see V2 (slice 3.4).
-- Column types mirror the JPA @Entity mappings so Hibernate `ddl-auto: validate` passes.

CREATE TABLE tax_rule_set (
                              id                            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                              name                          VARCHAR(120)   NOT NULL,
                              salary_exemption_cap          NUMERIC(15, 2) NOT NULL, -- §10.2
                              salary_exemption_divisor      INTEGER        NOT NULL, -- §10.2
                              disabled_child_threshold_bonus NUMERIC(15, 2) NOT NULL, -- §10.3
                              rebate_taxable_fraction       NUMERIC(5, 4)  NOT NULL, -- §10.5 (0.03)
                              rebate_eligible_fraction      NUMERIC(5, 4)  NOT NULL, -- §10.5 (0.15)
                              rebate_cap                    NUMERIC(15, 2) NOT NULL  -- §10.5 (1,000,000)
);

CREATE TABLE tax_assessment_year (
                                     id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                     label       VARCHAR(16) NOT NULL,
                                     rule_set_id BIGINT      NOT NULL,
                                     CONSTRAINT uq_assessment_year_label UNIQUE (label),
                                     CONSTRAINT fk_assessment_year_rule_set
                                         FOREIGN KEY (rule_set_id) REFERENCES tax_rule_set (id)
);

-- §10.4 — the 6 paying slabs (rows 2-7). The 0% threshold band is per-taxpayer
-- (category + disabled children), computed at calc time, not stored. `width` is
-- NULL for the open-ended "(rest)" top slab.
CREATE TABLE tax_slab (
                          id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                          rule_set_id BIGINT        NOT NULL,
                          ordinal     INTEGER       NOT NULL,
                          width       NUMERIC(15, 2),
                          rate        NUMERIC(5, 4) NOT NULL,
                          CONSTRAINT uq_slab_ruleset_ordinal UNIQUE (rule_set_id, ordinal),
                          CONSTRAINT fk_slab_rule_set
                              FOREIGN KEY (rule_set_id) REFERENCES tax_rule_set (id)
);

-- §10.3 — tax-free threshold per taxpayer category.
CREATE TABLE tax_category_threshold (
                                        id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                        rule_set_id BIGINT         NOT NULL,
                                        category    VARCHAR(32)    NOT NULL,
                                        amount      NUMERIC(15, 2) NOT NULL,
                                        CONSTRAINT uq_threshold_ruleset_category UNIQUE (rule_set_id, category),
                                        CONSTRAINT fk_threshold_rule_set
                                            FOREIGN KEY (rule_set_id) REFERENCES tax_rule_set (id)
);

-- §10.6 — minimum tax floor per location.
CREATE TABLE tax_minimum_tax_floor (
                                       id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                       rule_set_id BIGINT         NOT NULL,
                                       location    VARCHAR(48)    NOT NULL,
                                       amount      NUMERIC(15, 2) NOT NULL,
                                       CONSTRAINT uq_floor_ruleset_location UNIQUE (rule_set_id, location),
                                       CONSTRAINT fk_floor_rule_set
                                           FOREIGN KEY (rule_set_id) REFERENCES tax_rule_set (id)
);