-- V8: Zakat calculator schema (PLAN.md §13). No seed data — see V9.

CREATE TABLE zakat_rule_set (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name               VARCHAR(120)   NOT NULL,
    nisab_silver_grams NUMERIC(10, 4) NOT NULL,
    nisab_gold_grams   NUMERIC(10, 4) NOT NULL,
    resale_factor      NUMERIC(5, 4)  NOT NULL,
    rate_lunar         NUMERIC(5, 4)  NOT NULL,
    rate_solar         NUMERIC(5, 4)  NOT NULL
);

-- One row per (metal, carat); upserted on each BAJUS fetch (Slice 8.2).
CREATE TABLE metal_price (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    metal          VARCHAR(8)     NOT NULL,
    carat          VARCHAR(16)    NOT NULL,
    price_per_gram NUMERIC(12, 2) NOT NULL,
    source         VARCHAR(120),
    fetched_at     TIMESTAMP WITH TIME ZONE    NOT NULL,
    CONSTRAINT uq_metal_price_metal_carat UNIQUE (metal, carat)
);